apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-firefox-to-nginx
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: nginx
  ingress:
    - ports:
        - protocol: TCP
          port: 80