apiVersion: v1
kind: Pod
metadata:
  name: test-pv-pod
  labels:
    app.kubernetes.io/name: test-pv-pod
spec:
  containers:
  - name: test-pv-pod
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: azure-file-volume
    ports:
    - containerPort: 80
  volumes:
    - name: azure-file-volume
      persistentVolumeClaim:
        claimName: test-pvc

