apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
stringData:
  azurestorageaccountname: azurestorage00110011
  azurestorageaccountkey: ifNwaG+HuK80ix2/d/laEdLzT53rY4UF6cJfbRz6S7kL7pzf6pnfA3HdEmQTHs/+h9wNhlcMEHpK+AStDLFcOw==